Arieen17/about mobile resp
acm-ucr/saf-website pull request #60
Opened 2024-01-27 06:43 UTC by arieen17

<img width="793" alt="image" src="https://github.com/acm-ucr/saf-website/assets/148610393/b91b01b9-e070-4872-af1c-8996d4a61ca2">
<img width="306" alt="image" src="https://github.com/acm-ucr/saf-website/assets/148610393/f491d4c1-f49d-4446-9935-f19ff0e60030">

I figured out a way to keep the mandala from keeping its shape and not squashing together when switched to mobile screen. I kept it this way to keep it consistent from computer to mobile, but let me know if you would rather have the mandala gone when on a mobile screen.

2024-01-27 08:05 UTC, SafeDuck requested changes

2024-01-27 08:05 UTC, SafeDuck commented on src/app/about/page.js
> +        text={
Thanks for putting in the text, but this is someone else's issue. You can revert your changes to how it was before

2024-01-27 08:05 UTC, SafeDuck commented on src/components/Photo.jsx
> +        className="w-2/5 absolute z-1 -right-[-5%]"
check discord comments

2024-01-30 07:20 UTC, arieen17 commented
<img width="389" alt="image" src="https://github.com/acm-ucr/saf-website/assets/148610393/7f5de324-1e63-4bd7-9a6d-283a25dd95ee">
<img width="1169" alt="image" src="https://github.com/acm-ucr/saf-website/assets/148610393/c6357dff-655a-478f-9b28-f4f28ad2fbbc">

2024-01-30 21:29 UTC, SafeDuck approved these changes

2024-01-30 21:29 UTC, merged